name: Tests
on:
  push:
    branches:
      - master
      - main
      - track/**

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/test.yaml
  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/integration_test.yaml
