name: Test and publish to edge

on:
  push:
    branches:
      - master
      - main
      - track/**

jobs:
  tests:
    name: Run the tests
    uses: ./.github/workflows/ci.yaml

  publish-charm:
    name: Publish Charm
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.3
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
